// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1BOEuQNTtNS3JHl3sRpn9XcaXASXG8_g',
    appId: '1:890392750705:web:f02a8e232560b5d91c89d0',
    messagingSenderId: '890392750705',
    projectId: 'split-hawk',
    authDomain: 'split-hawk.firebaseapp.com',
    storageBucket: 'split-hawk.firebasestorage.app',
    measurementId: 'G-RZMDL8MHHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdKGEw-9cbF9leIT1MkOdDACTTf-NKHNY',
    appId: '1:890392750705:android:119e3650a69273381c89d0',
    messagingSenderId: '890392750705',
    projectId: 'split-hawk',
    storageBucket: 'split-hawk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1h7RyZrybcIcyxs7Aull0qTwrpAvPgK4',
    appId: '1:890392750705:ios:81367ef0bda178d11c89d0',
    messagingSenderId: '890392750705',
    projectId: 'split-hawk',
    storageBucket: 'split-hawk.firebasestorage.app',
    iosBundleId: 'com.example.splithawk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1h7RyZrybcIcyxs7Aull0qTwrpAvPgK4',
    appId: '1:890392750705:ios:81367ef0bda178d11c89d0',
    messagingSenderId: '890392750705',
    projectId: 'split-hawk',
    storageBucket: 'split-hawk.firebasestorage.app',
    iosBundleId: 'com.example.splithawk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1BOEuQNTtNS3JHl3sRpn9XcaXASXG8_g',
    appId: '1:890392750705:web:31bb4e5ebdd7ac911c89d0',
    messagingSenderId: '890392750705',
    projectId: 'split-hawk',
    authDomain: 'split-hawk.firebaseapp.com',
    storageBucket: 'split-hawk.firebasestorage.app',
    measurementId: 'G-77LCHX2JM5',
  );
}
